using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Caching.Memory;

namespace LogiLearn.Endpoints.V1.Gists;

using Contracts.V1;
using Domain;
using Endpoints.Attributes;
using Infrastructure.GithubServices;

public static class GithubGistsEndpoints
{
    record GistEdnpoints;
    public static IEndpointRouteBuilder MapGithubGistsEndpoints(this IEndpointRouteBuilder route)
    {
        route.MapGet("/circuits", async (
            HttpContext context,
            IMemoryCache cache,
            [FromServices]IGithubClientBuilder builder,
            int page = 1) =>
        {
            var token = context.Request.Cookies["session"];
            if (token is null)
                return Results.Unauthorized();

            var cacheKey = $"{SHA256.HashData(Encoding.UTF8.GetBytes(token))}_gists";
            var circs = await cache.GetOrCreateAsync(cacheKey, async entry =>
            {
                var client = builder.GetClient(token);
                var response = await client.GetAsync($"/gists?per_page=12&page={page}");

                if (!response.IsSuccessStatusCode)
                    return null;
                
                var gists = await response.Content.ReadFromJsonAsync<GithubGist[]>();
                var circs = 
                    from gist in gists
                    where CircuitFile.ValidateFiles([ ..gist.Files.Keys ])
                    select gist;
                
                return circs;
            });

            if (circs is null)
                return Results.StatusCode(502);
            
            return Results.Ok(circs);
        }).WithMetadata(new RequireCSRFTokenAttribute());

        route.MapGet("/circuits/{id}", async (string id,
            HttpContext context,
            [FromServices]IGithubClientBuilder builder) =>
        {
            var token = context.Request.Cookies["session"];
            if (token is null)
                return Results.Unauthorized();
            
            var client = builder.GetClient(token);
            
            var response = await client.GetAsync($"/gists/{id}");

            if (!response.IsSuccessStatusCode)
                return Results.StatusCode(502);
            
            var gist = await response.Content.ReadFromJsonAsync<GithubGist>();
            if (gist is null)
                return Results.NotFound();

            var circuit = gist.Files
                .FirstOrDefault(f => CircuitFile.ValidateFile(f.Key));
            if (circuit.Key is null)
                return Results.BadRequest("The gist is not a valid circuit.");
            
            return Results.Ok(new {
                circuit = circuit.Value.Content,
                description = gist.Description
            });
        });

        route.MapPost("/circuits", async (HttpContext context,
            IConfiguration configuration,
            IMemoryCache cache,
            ILogger<GistEdnpoints> logger,
            [FromServices]IGithubClientBuilder builder) =>
        {
            var token = context.Request.Cookies["session"];
            if (token is null)
                return Results.Unauthorized();
            
            var cacheKey = $"{SHA256.HashData(Encoding.UTF8.GetBytes(token))}_gists";
            cache.Remove(cacheKey);

            var client = builder.GetClient(token);

            var circuit = new CreateGistData {
                Description = $"A circuit generated by Logilearn ({configuration["FRONTEND_URL"]}).",
                Public = true,
                Files = new() {
                    { CircuitFile.GetNewName(), new() { Content = CircuitFile.GetNewContent() } }
                }
            };
            
            var response = await client.PostAsJsonAsync($"/gists", circuit);

            if (!response.IsSuccessStatusCode)
            {
                if (logger.IsEnabled(LogLevel.Error))
                    logger.LogError("Error o POST /gists: {error}", 
                        await response.Content.ReadAsStringAsync());
                
                return Results.StatusCode(502);
            }
            
            var gist = await response.Content.ReadFromJsonAsync<GithubGist>();
            if (gist is null)
                return Results.NotFound();

            return Results.Ok(gist);
        }).WithMetadata(new RequireCSRFTokenAttribute());

        route.MapPut("/circuits/{id}", async (string id,
            HttpContext context,
            IMemoryCache cache,
            ILogger<GistEdnpoints> logger,
            [FromServices]IGithubClientBuilder builder,
            [FromBody]CircuitToSave circuit) =>
        {
            var token = context.Request.Cookies["session"];
            if (token is null)
                return Results.Unauthorized();
            
            var cacheKey = $"{SHA256.HashData(Encoding.UTF8.GetBytes(token))}_gists";
            cache.Remove(cacheKey);
            
            var client = builder.GetClient(token);

            var payload = new UpdateGistData {
                Description = circuit.Description,
                Files = new() {
                    { CircuitFile.GetNewName(), new() { Content = circuit.Circuit } }
                }
            };

            var response =  await client.PatchAsJsonAsync($"/gists/{id}", payload);

            if (!response.IsSuccessStatusCode)
            {
                if (logger.IsEnabled(LogLevel.Error))
                    logger.LogError("Error o POST /gists: {error}", 
                        await response.Content.ReadAsStringAsync());
                
                return Results.StatusCode(502);
            }

            return Results.Ok();
        }).WithMetadata(new RequireCSRFTokenAttribute());

        return route;
    }
}