# BUILD
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /LogiLearn

COPY /LogiLearn/LogiLearn.csproj /LogiLearn/
RUN dotnet restore /LogiLearn/LogiLearn.csproj

COPY /LogiLearn /LogiLearn/
WORKDIR /LogiLearn
RUN dotnet publish -c Release -o /app/publish


# RUNTIME
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "LogiLearn.dll"]